#!/bin/sh

if [[ $# < 1 ]];then
    echo "plslook pattern - look for song on mpd playlist"
    echo "plslook play pattern - play first match of such a lookup"
elif [[ "$1" == "play" ]];then
    pattern="$2"
    match=1
    if [[ $# > 2 ]];then
        match=$3
    fi
    mpc play $(mpc playlist | nl -n ln | grep -i "$pattern" | head -n $match | cut -d' ' -f1)
else
    mpc playlist | nl | grep -i "$1"
fi
