" My way for using Vim. As simple as possible.
" Bartek Lew

set encoding=utf8
set autoindent
set number
set expandtab
set backspace=indent,eol,start
set ruler
set laststatus=2
set cursorline

let mapleader="-"
:highlight Folded ctermbg=blue ctermfg=white

" Allow <tab> character in makefile files.
autocmd Bufenter Makefile,makefile :set noexpandtab

" Load Gtags from GNU Global for symbols lookup.
" I want no quickfix window after each call.
let g:Gtags_OpenQuickfixWindow = 0
source ~/.vim/gtags.vim

" Dead simple symbol lookup:
" Find Symbol, Find Reference, Find Declaration
noremap <leader>fs :Gtags <c-r><c-w><cr>
noremap <leader>fr :Gtags -rx <c-r><c-w><cr>
noremap <leader>fd ?[a-zA-Z0-9_]\s\+<c-r><c-w>[^a-zA-Z0-9_]<cr>

" Working on raw text:
" Text Substitute
noremap <leader>ts :%s#<c-r><c-w>
noremap <leader>tS :s#<c-r><c-w>

" Text Grep
map <leader>tg <leader>-g <c-r><c-w> %:h

" Text Find
noremap <leader>tf /<c-r><c-w><cr>
noremap <leader>tF :split<cr>/<c-r><c-w><cr>

" Goto Declaration/Import
noremap <leader>gd ?\a\(\s\\|\*\)*<c-r><c-w><cr>
autocmd Bufenter *.java noremap <leader>gi ?import.*\.<c-r><c-w><cr>

" indenting
set tabstop=4
set shiftwidth=4
set smartindent
" But for ruby:
autocmd Bufenter *.rb set tabstop=2
autocmd Bufenter *.rb set shiftwidth=2

" Remap scrolling and moving windows
noremap <c-j> <c-e>
noremap <c-k> <c-y>
noremap <c-h> :bp<cr>
noremap <c-l> :bn<cr>

" Window Close
noremap <leader>wc <c-w>c

"split small/big
noremap <leader>ss :split<cr>:resize 10<cr>
noremap <leader>sS :split<cr>:resize 5<cr>
noremap <leader>sb :split<cr>:resize 25<cr>

" Config Edit/Apply
noremap <leader>ce :split $MYVIMRC<cr>
noremap <leader>ca :source $MYVIMRC<cr>

" How grep should be called:
noremap <leader>-g :grep --binary-files=without-match --exclude="CVS/*" -Rn

" Line (Un-)Comment
autocmd Bufenter *.tex noremap <leader>lc :s#^#%#<cr>
autocmd Bufenter *.tex noremap <leader>luc :s#^%##<cr>
autocmd Bufenter *.c,*.h,*.css noremap <leader>lc :s#^\(.*\)$#/*\1*/#<cr>
autocmd Bufenter *.c,*.h,*.css noremap <leader>luc :s#^\s*/\*\(.*\)\*/\s*$#\1#<cr>

" Line Indent
vnoremap <c-t> :s/^/    /<cr>
vnoremap <c-d> :s/^    //<cr>

" Open Header/Source
autocmd Bufenter *.c,*.cpp noremap <leader>oh :vsplit %:p:r.h<cr>
autocmd Bufenter *.h noremap <leader>os :vsplit %:p:r.c<cr>
noremap <leader>od :vsplit %:h


" List Show, Next, Previous, Goto
noremap <leader>ls :clist<cr>
noremap <leader>ln :cnext<cr>
noremap <leader>lp :cprevious<cr>
noremap <leader>lg :cc

" Shell Ls
noremap <leader>sl :! ls 

" Window Split
noremap <leader>ws :vsplit
noremap <leader>wS :split

" Buffer list/set and close (without closing window)
noremap <leader>bl :buffers<cr>
noremap <leader>bs :buffers<cr>:b
noremap <leader>bc :b#<cr>:bd#<cr>

"Fold Brace
noremap <leader>fb V%zf

" Delete File
noremap <leader>df :!rm %<cr>
