" My way for using Vim. As simple as possible.
" Bartek Lew

set encoding=utf8
set autoindent
set number
set expandtab
set backspace=indent,eol,start
set ruler
syntax off

noremap <left> :tabp<cr>
noremap <right> :tabn<cr>
noremap <c-right> :tabe
noremap <up> ?
noremap <down> /
noremap -hc :nohl<cr>

noremap -ce :e ~/.vimrc<cr>
noremap -ca :source ~/.vimrc<cr>
noremap -cs :! "$HOME/.local/bin/sync.sh"<cr>

noremap <c-g> :grep '<c-r><c-w>' .<cr>
