#!/bin/sh -e

[ -e /tmp/pcl.in ] && [ -e /tmp/pcl.out ] || {
	echo "pipe-cl not ran" >&2
	exit 1
}

echo "example pipe-cl client"
echo "write input and hit CTRL-D"
echo

while true
do
	echo ">"
	cat > /tmp/pcl.in
	cat /tmp/pcl.out
done

