#!/bin/bash 

imageviewer=eog
pdfviewer=evince

function drop(){
    rm $1 "$file"
}

function movie(){
    mv "$file" ~/doc/filmy
}

function clean(){
    for file in "$1"/*;
    do
        if [[ -d "$file" ]]; then
            clean "$file"
        fi

        echo "Do for: $file"
        dealt=0
    
        while [[ -e "$file" ]] && [[ $dealt == 0 ]]; do 
            if [[ $(file -ib "$file" | grep image) ]];then
                $imageviewer "$file"
            elif [[ $(echo $file | grep -e '\.pdf$' ) ]];then
                $pdfviewer "$file"
            fi
    
            echo -n ">"
            read -e command
    
            if [[ "$command" == "keep" ]]; then
                dealt=1
            else
                eval "$command"
            fi
        done
    done
}

if [[ -d "$1" ]]; then
    clean "$1"
else
    clean *
fi
