#!/bin/sh

if [[ $# != 1 ]];then
    echo "USAGE: names extension"
    echo "lists all filenames in directory"
    exit 1
fi

extension=$1
for file in *.$extension
do
    filename=${file%.$extension}
    echo $filename
done | uniq
