#!/bin/sh

cd ~/Downloads
while read link; do
    flags=''
    echo $link | grep -P ^audio
    if [[ $? == '0' ]]; then
        link=$(echo $link | sed s/^audio//)
        flags='-x'
    fi

    tmpfile=/tmp/ytget-$RANDOM
    youtube-dl $flags "$link" | tee $tmpfile
    export file=$(cat $tmpfile | grep ffmpeg | head -n1 | cut -d'"' -f2)
    rm $tmpfile

    mpc pause
    mplayer "$file" > /dev/null
    echo "what now with $file?"
    $SHELL
done

