#!/bin/sh -x

cd ~/Downloads
while read link; do
    flags=''
    echo $link | grep -P ^audio
    if [[ $? == '0' ]]; then
        link=$(echo $link | sed s/^audio//)
        flags='-x'
    fi

    file=$(youtube-dl $flags "$link" | grep ffmpeg | head -n1 | cut -d'"' -f2)

    mpc pause
    mplayer "$file" > /dev/null
    echo "what now with $file?"
    $SHELL
done

